systemctl --user start udiskie.service & #for automounting usb drives
nm-applet &
nmcli con up CoudBe & #try connecting to Coudbe if up
blueman-applet &
xrdb -load ~/.Xresources &
numlockx on &
feh --bg-fill --randomize ~/wallpapers/
xset -b &
flameshot &
picom -CG --experimental-backends &
pkill clipit; clipit -n &

betterlockscreen -l blur --time-format "%I:%M %p"

if which xfce4-session; then
  exec startxfce4
elif which awesome; then
  exec awesome
elif which bspwm; then
  exec bspwm
elif which sway;then
  sway --my-next-gpu-wont-be-nvidia
elif which dwm;then
  exec dwmblocks &
  exec dbus-launch dwm #dbus-launch needed for notifications to work
else
  echo "No WM's Found !!"
fi
